import type { Animal, Farm } from "@/lib/api";

/** Static catalog used when the live API is unreachable. */
export const DEMO_FARMS: Farm[] = [
  {
    id: "demo-farm-1",
    name: "Green Pastures Farm",
    slug: "green-pastures-farm",
    description:
      "Family-run livestock farm in Kasur with transparent care logs and Shariah-aligned profit sharing.",
    location: "Kasur Road, Near Balloki",
    city: "Kasur",
    province: "Punjab",
    imageUrl: "/images/farms/green-pastures.jpg",
    status: "APPROVED",
    owner: { fullName: "Imran Malik" },
    _count: { animals: 7, reviews: 0 },
  },
  {
    id: "demo-farm-2",
    name: "Indus Valley Livestock",
    slug: "indus-valley-livestock",
    description:
      "Verified cattle and goat farm near Multan specializing in healthy Beetal goats and Sahiwal cows.",
    location: "Bosan Road",
    city: "Multan",
    province: "Punjab",
    imageUrl: "/images/farms/indus-valley.jpg",
    status: "APPROVED",
    owner: { fullName: "Sara Ahmed" },
    _count: { animals: 7, reviews: 0 },
  },
];

export const DEMO_ANIMALS: Animal[] = [
  {
    id: "demo-goat-1",
    name: "Beetal Buck — Noor",
    slug: "beetal-buck-noor",
    species: "GOAT",
    breed: "Beetal",
    ageMonths: 18,
    weightKg: 55,
    pricePkr: 85000,
    sharePricePkr: 85000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 22,
    description: "Healthy Beetal buck ready for fattening cycle.",
    imageUrl: "/images/animals/goat-6.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-goat-2",
    name: "Teddy Doe — Chameli",
    slug: "teddy-doe-chameli",
    species: "GOAT",
    breed: "Teddy",
    ageMonths: 12,
    weightKg: 28,
    pricePkr: 48000,
    sharePricePkr: 48000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 20,
    description: "Young Teddy doe under supervised farm care.",
    imageUrl: "/images/animals/goat-1.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-goat-3",
    name: "Kamori Doe — Gul",
    slug: "kamori-doe-gul",
    species: "GOAT",
    breed: "Kamori",
    ageMonths: 16,
    weightKg: 42,
    pricePkr: 72000,
    sharePricePkr: 72000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 19,
    description: "Kamori doe with strong milk potential.",
    imageUrl: "/images/animals/goat-2.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-cow-1",
    name: "Sahiwal Heifer — Rani",
    slug: "sahiwal-heifer-rani",
    species: "COW",
    breed: "Sahiwal",
    ageMonths: 22,
    weightKg: 260,
    pricePkr: 260000,
    sharePricePkr: 65000,
    totalShares: 4,
    availableShares: 4,
    expectedRoiPercent: 16,
    description: "Sahiwal heifer listed in share units.",
    imageUrl: "/images/animals/cow-6.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-cow-2",
    name: "Cholistani Cow — Moti",
    slug: "cholistani-cow-moti",
    species: "COW",
    breed: "Cholistani",
    ageMonths: 30,
    weightKg: 320,
    pricePkr: 310000,
    sharePricePkr: 77500,
    totalShares: 4,
    availableShares: 3,
    expectedRoiPercent: 15,
    description: "Mature Cholistani cow with daily care updates.",
    imageUrl: "/images/animals/cow-1.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-sheep-1",
    name: "Kajli Sheep — Sitara",
    slug: "kajli-sheep-sitara",
    species: "SHEEP",
    breed: "Kajli",
    ageMonths: 14,
    weightKg: 45,
    pricePkr: 52000,
    sharePricePkr: 52000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 18,
    description: "Kajli sheep from Green Pastures herd.",
    imageUrl: "/images/animals/sheep-1.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-1",
      name: "Green Pastures Farm",
      slug: "green-pastures-farm",
      city: "Kasur",
      province: "Punjab",
    },
  },
  {
    id: "demo-cow-3",
    name: "Sahiwal Cow — Laila",
    slug: "sahiwal-cow-laila",
    species: "COW",
    breed: "Sahiwal",
    ageMonths: 36,
    weightKg: 380,
    pricePkr: 420000,
    sharePricePkr: 84000,
    totalShares: 5,
    availableShares: 5,
    expectedRoiPercent: 14,
    description: "Dairy Sahiwal cow from Indus Valley.",
    imageUrl: "/images/animals/cow-2.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-2",
      name: "Indus Valley Livestock",
      slug: "indus-valley-livestock",
      city: "Multan",
      province: "Punjab",
    },
  },
  {
    id: "demo-cow-4",
    name: "Friesian Cross — Sohni",
    slug: "friesian-cross-sohni",
    species: "COW",
    breed: "Friesian Cross",
    ageMonths: 28,
    weightKg: 350,
    pricePkr: 390000,
    sharePricePkr: 78000,
    totalShares: 5,
    availableShares: 4,
    expectedRoiPercent: 17,
    description: "High-yield Friesian cross listed for investment.",
    imageUrl: "/images/animals/cow-3.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-2",
      name: "Indus Valley Livestock",
      slug: "indus-valley-livestock",
      city: "Multan",
      province: "Punjab",
    },
  },
  {
    id: "demo-goat-4",
    name: "Beetal Doe — Roshni",
    slug: "beetal-doe-roshni",
    species: "GOAT",
    breed: "Beetal",
    ageMonths: 15,
    weightKg: 38,
    pricePkr: 62000,
    sharePricePkr: 62000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 21,
    description: "Beetal doe from Multan farm stock.",
    imageUrl: "/images/animals/goat-3.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-2",
      name: "Indus Valley Livestock",
      slug: "indus-valley-livestock",
      city: "Multan",
      province: "Punjab",
    },
  },
  {
    id: "demo-sheep-2",
    name: "Thalli Sheep — Heer",
    slug: "thalli-sheep-heer",
    species: "SHEEP",
    breed: "Thalli",
    ageMonths: 11,
    weightKg: 36,
    pricePkr: 44000,
    sharePricePkr: 44000,
    totalShares: 1,
    availableShares: 1,
    expectedRoiPercent: 18,
    description: "Thalli sheep ready for seasonal cycle.",
    imageUrl: "/images/animals/sheep-2.jpg",
    status: "LISTED",
    farm: {
      id: "demo-farm-2",
      name: "Indus Valley Livestock",
      slug: "indus-valley-livestock",
      city: "Multan",
      province: "Punjab",
    },
  },
];

export function filterDemoAnimals(species?: string, limit = 24): Animal[] {
  const list = species
    ? DEMO_ANIMALS.filter((a) => a.species === species.toUpperCase())
    : DEMO_ANIMALS;
  return list.slice(0, limit);
}

export function getDemoAnimal(slug: string): Animal | undefined {
  return DEMO_ANIMALS.find((a) => a.slug === slug);
}

export function getDemoFarm(slug: string): Farm | undefined {
  const farm = DEMO_FARMS.find((f) => f.slug === slug);
  if (!farm) return undefined;
  return {
    ...farm,
    animals: DEMO_ANIMALS.filter((a) => a.farm.slug === slug),
  };
}
